version: "3.8"

networks:

  public:
    name: public
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

services:

  pods-proxy:
    image: pods-proxy
    restart: on-failure
    build: ./proxy
    container_name: pods-proxy
    hostname: pods-proxy
    networks:
      public:
    volumes:
      - /etc/letsencrypt/live/dev.martinweise.at/fullchain.pem:/certs/fullchain.pem
      - /etc/letsencrypt/live/dev.martinweise.at/privkey.pem:/certs/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: json-file

  pods-pods:
    image: solidproject/community-server
    container_name: pods-pods
    hostname: pods-pods
    networks:
      public:
    logging:
      driver: json-file
